"""
ProtonMail IMAP/SMTP client for MCP server.

This version uses standard IMAP/SMTP protocols via ProtonMail Bridge
instead of the unofficial API client.
"""

import imaplib
import smtplib
import email
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.header import decode_header
from typing import Optional, List, Dict, Any
from datetime import datetime
import re


class ProtonMailClientIMAP:
    """
    ProtonMail client using IMAP/SMTP via ProtonMail Bridge.
    
    This is more reliable than the unofficial API client as it uses
    ProtonMail's official Bridge application.
    """
    
    def __init__(
        self,
        imap_server: str = "127.0.0.1",
        imap_port: int = 1143,
        smtp_server: str = "127.0.0.1",
        smtp_port: int = 1025
    ):
        """
        Initialize the IMAP/SMTP client.
        
        Args:
            imap_server: IMAP server address (default: Bridge local)
            imap_port: IMAP port (default: 1143 for Bridge)
            smtp_server: SMTP server address (default: Bridge local)
            smtp_port: SMTP port (default: 1025 for Bridge)
        """
        self.imap_server = imap_server
        self.imap_port = imap_port
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port
        
        self.imap: Optional[imaplib.IMAP4] = None
        self.username: Optional[str] = None
        self.password: Optional[str] = None
        self._authenticated = False
    
    def authenticate(self, username: str, password: str) -> bool:
        """
        Authenticate with ProtonMail Bridge.
        
        Args:
            username: Bridge username (usually your ProtonMail address)
            password: Bridge password (generated by Bridge app)
            
        Returns:
            True if authentication successful
        """
        try:
            self.username = username
            self.password = password
            
            # Connect to IMAP server
            print(f"Connecting to IMAP server at {self.imap_server}:{self.imap_port}...")
            self.imap = imaplib.IMAP4(self.imap_server, self.imap_port)
            
            # Login
            print(f"Logging in as {username}...")
            self.imap.login(username, password)
            
            self._authenticated = True
            print("✓ IMAP authentication successful!")
            return True
            
        except imaplib.IMAP4.error as e:
            print(f"❌ IMAP authentication failed: {e}")
            self._authenticated = False
            return False
        except Exception as e:
            print(f"❌ Connection failed: {e}")
            self._authenticated = False
            return False
    
    def _ensure_authenticated(self):
        """Raise exception if not authenticated."""
        if not self._authenticated or not self.imap:
            raise Exception("Not authenticated. Please call authenticate() first.")
    
    def _decode_header(self, header: str) -> str:
        """Decode email header."""
        if not header:
            return ""
        
        decoded_parts = decode_header(header)
        result = []
        
        for content, encoding in decoded_parts:
            if isinstance(content, bytes):
                if encoding:
                    result.append(content.decode(encoding))
                else:
                    result.append(content.decode('utf-8', errors='ignore'))
            else:
                result.append(str(content))
        
        return ' '.join(result)
    
    def get_messages(
        self,
        limit: int = 50,
        folder: str = "INBOX"
    ) -> List[Dict[str, Any]]:
        """
        Get messages from a folder.
        
        Args:
            limit: Maximum number of messages to retrieve
            folder: IMAP folder name (default: INBOX)
            
        Returns:
            List of message dictionaries
        """
        self._ensure_authenticated()
        
        try:
            # Select folder
            self.imap.select(folder)
            
            # Search for all messages
            _, message_numbers = self.imap.search(None, 'ALL')
            
            if not message_numbers[0]:
                return []
            
            # Get message IDs (newest first)
            msg_ids = message_numbers[0].split()
            msg_ids = msg_ids[-limit:] if len(msg_ids) > limit else msg_ids
            msg_ids = list(reversed(msg_ids))
            
            result = []
            
            for msg_id in msg_ids:
                # Fetch message headers
                _, msg_data = self.imap.fetch(msg_id, '(RFC822.HEADER)')
                
                if not msg_data or not msg_data[0]:
                    continue
                
                # Parse headers
                email_msg = email.message_from_bytes(msg_data[0][1])
                
                subject = self._decode_header(email_msg.get('Subject', ''))
                from_header = self._decode_header(email_msg.get('From', ''))
                date_str = email_msg.get('Date', '')
                
                # Extract email address from "Name <email>" format
                sender_match = re.search(r'<(.+?)>', from_header)
                sender = sender_match.group(1) if sender_match else from_header
                
                # Parse date
                try:
                    date_tuple = email.utils.parsedate_tz(date_str)
                    if date_tuple:
                        timestamp = email.utils.mktime_tz(date_tuple)
                    else:
                        timestamp = 0
                except:
                    timestamp = 0
                
                result.append({
                    "id": msg_id.decode(),
                    "subject": subject or "(No Subject)",
                    "sender": sender,
                    "sender_name": from_header.split('<')[0].strip() if '<' in from_header else sender,
                    "time": timestamp,
                    "unread": True,  # Would need FLAGS to determine
                    "snippet": ""  # Would need to fetch body
                })
            
            return result
            
        except Exception as e:
            raise Exception(f"Failed to get messages: {e}")
    
    def read_message(self, message_id: str) -> Dict[str, Any]:
        """
        Read the full content of a specific message.
        
        Args:
            message_id: The IMAP message ID
            
        Returns:
            Dictionary with full message details
        """
        self._ensure_authenticated()
        
        try:
            # Fetch full message
            _, msg_data = self.imap.fetch(message_id, '(RFC822)')
            
            if not msg_data or not msg_data[0]:
                raise Exception("Message not found")
            
            # Parse message
            email_msg = email.message_from_bytes(msg_data[0][1])
            
            # Extract headers
            subject = self._decode_header(email_msg.get('Subject', ''))
            from_header = self._decode_header(email_msg.get('From', ''))
            to_header = self._decode_header(email_msg.get('To', ''))
            cc_header = self._decode_header(email_msg.get('Cc', ''))
            date_str = email_msg.get('Date', '')
            
            # Extract email addresses
            sender_match = re.search(r'<(.+?)>', from_header)
            sender = sender_match.group(1) if sender_match else from_header
            
            # Parse recipients
            recipients = [addr.strip() for addr in to_header.split(',') if addr.strip()]
            cc_recipients = [addr.strip() for addr in cc_header.split(',') if addr.strip()] if cc_header else []
            
            # Parse date
            try:
                date_tuple = email.utils.parsedate_tz(date_str)
                timestamp = email.utils.mktime_tz(date_tuple) if date_tuple else 0
            except:
                timestamp = 0
            
            # Extract body
            body = ""
            if email_msg.is_multipart():
                for part in email_msg.walk():
                    content_type = part.get_content_type()
                    if content_type == "text/plain":
                        payload = part.get_payload(decode=True)
                        if payload:
                            body = payload.decode('utf-8', errors='ignore')
                            break
                    elif content_type == "text/html" and not body:
                        payload = part.get_payload(decode=True)
                        if payload:
                            body = payload.decode('utf-8', errors='ignore')
            else:
                payload = email_msg.get_payload(decode=True)
                if payload:
                    body = payload.decode('utf-8', errors='ignore')
            
            # Count attachments
            attachments = []
            if email_msg.is_multipart():
                for part in email_msg.walk():
                    if part.get_content_disposition() == 'attachment':
                        filename = part.get_filename()
                        if filename:
                            attachments.append(self._decode_header(filename))
            
            return {
                "id": message_id,
                "subject": subject or "(No Subject)",
                "sender": sender,
                "sender_name": from_header.split('<')[0].strip() if '<' in from_header else sender,
                "recipients": recipients,
                "cc": cc_recipients,
                "time": timestamp,
                "body": body,
                "attachments": len(attachments),
                "attachment_names": attachments
            }
            
        except Exception as e:
            raise Exception(f"Failed to read message: {e}")
    
    def send_message(
        self,
        to: List[str],
        subject: str,
        body: str,
        cc: Optional[List[str]] = None,
        bcc: Optional[List[str]] = None,
        is_html: bool = False
    ) -> Dict[str, Any]:
        """
        Send an email via ProtonMail Bridge SMTP.
        
        Args:
            to: List of recipient email addresses
            subject: Email subject
            body: Email body (plain text or HTML)
            cc: Optional list of CC recipients
            bcc: Optional list of BCC recipients
            is_html: Whether the body is HTML
            
        Returns:
            Dictionary with send status
        """
        self._ensure_authenticated()
        
        try:
            # Create message
            if is_html:
                msg = MIMEMultipart('alternative')
                msg.attach(MIMEText(body, 'html'))
            else:
                msg = MIMEText(body, 'plain')
            
            msg['Subject'] = subject
            msg['From'] = self.username
            msg['To'] = ', '.join(to)
            
            if cc:
                msg['Cc'] = ', '.join(cc)
            
            # All recipients (to + cc + bcc)
            all_recipients = to + (cc or []) + (bcc or [])
            
            # Connect to SMTP server
            smtp = smtplib.SMTP(self.smtp_server, self.smtp_port)
            smtp.login(self.username, self.password)
            
            # Send message
            smtp.send_message(msg, to_addrs=all_recipients)
            smtp.quit()
            
            return {
                "success": True,
                "message_id": msg.get('Message-ID', 'unknown'),
                "status": "sent",
                "timestamp": datetime.now().isoformat()
            }
            
        except Exception as e:
            raise Exception(f"Failed to send message: {e}")
    
    def search_messages(
        self,
        query: str,
        limit: int = 20
    ) -> List[Dict[str, Any]]:
        """
        Search messages for a query string.
        
        Uses IMAP SEARCH command with text search.
        
        Args:
            query: Search query string
            limit: Maximum number of results
            
        Returns:
            List of matching messages
        """
        self._ensure_authenticated()
        
        try:
            # Select inbox
            self.imap.select("INBOX")
            
            # Search for messages containing the query
            # IMAP SEARCH TEXT searches in subject and body
            _, message_numbers = self.imap.search(None, f'TEXT "{query}"')
            
            if not message_numbers[0]:
                return []
            
            # Get message IDs (newest first)
            msg_ids = message_numbers[0].split()
            msg_ids = msg_ids[-limit:] if len(msg_ids) > limit else msg_ids
            msg_ids = list(reversed(msg_ids))
            
            results = []
            
            for msg_id in msg_ids:
                # Fetch message headers
                _, msg_data = self.imap.fetch(msg_id, '(RFC822.HEADER BODY.PEEK[TEXT]<0.200>)')
                
                if not msg_data or not msg_data[0]:
                    continue
                
                # Parse headers
                email_msg = email.message_from_bytes(msg_data[0][1])
                
                subject = self._decode_header(email_msg.get('Subject', ''))
                from_header = self._decode_header(email_msg.get('From', ''))
                date_str = email_msg.get('Date', '')
                
                sender_match = re.search(r'<(.+?)>', from_header)
                sender = sender_match.group(1) if sender_match else from_header
                
                try:
                    date_tuple = email.utils.parsedate_tz(date_str)
                    timestamp = email.utils.mktime_tz(date_tuple) if date_tuple else 0
                except:
                    timestamp = 0
                
                # Get snippet from body preview
                snippet = ""
                if len(msg_data[0]) > 1 and msg_data[0][1]:
                    snippet = msg_data[0][1].decode('utf-8', errors='ignore')[:200]
                
                results.append({
                    "id": msg_id.decode(),
                    "subject": subject or "(No Subject)",
                    "sender": sender,
                    "sender_name": from_header.split('<')[0].strip() if '<' in from_header else sender,
                    "time": timestamp,
                    "snippet": snippet
                })
            
            return results
            
        except Exception as e:
            raise Exception(f"Search failed: {e}")
    
    def delete_message(self, message_id: str) -> bool:
        """
        Delete a message (mark for deletion).
        
        Args:
            message_id: IMAP message ID
            
        Returns:
            True if successful
        """
        self._ensure_authenticated()
        
        try:
            # Mark message as deleted
            self.imap.store(message_id, '+FLAGS', '\\Deleted')
            # Expunge to permanently delete
            self.imap.expunge()
            return True
        except Exception as e:
            raise Exception(f"Failed to delete message: {e}")
    
    def get_folders(self) -> List[Dict[str, Any]]:
        """
        Get list of IMAP folders.
        
        Returns:
            List of folder information
        """
        self._ensure_authenticated()
        
        try:
            _, folders = self.imap.list()
            
            result = []
            for folder in folders:
                # Parse folder name from IMAP response
                # Format: (\\HasNoChildren) "/" "INBOX"
                folder_str = folder.decode()
                match = re.search(r'"([^"]+)"$', folder_str)
                if match:
                    folder_name = match.group(1)
                    result.append({
                        "name": folder_name,
                        "id": folder_name
                    })
            
            return result
            
        except Exception as e:
            raise Exception(f"Failed to get folders: {e}")
    
    def close(self):
        """Close the IMAP connection."""
        if self.imap:
            try:
                self.imap.close()
                self.imap.logout()
            except:
                pass
